### ISSUE TITLE
Database reconnect after connection is lost

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/object-service#21]
Currently, there's no reconnect mechanism.

**Comment by LeanderK** [comment]
working on it, its more difficult than one would think.

**Comment by LeanderK** [comment]
should be fixed with #23

**Comment by kelunik** [comment]
Not fixed yet in current master.

`[qtp940583692-21] WARN com.mchange.v2.c3p0.impl.NewPooledConnection - [c3p0] A PooledConnection that has already signalled a Connection error is still in use!`

**Comment by kelunik** [comment]
For testing:
- `gradle run`
- `sudo service mysql restart`
- `http localhost:4567/tempaltes`

**Comment by LeanderK** [comment]
another try with #29

**Comment by LeanderK** [comment]
another try with #30

**Comment by kelunik** [comment]
Still doesn't work after `mysql` restart.

**Comment by LeanderK** [comment]
this was way more complicated than it should be. But i think i figured it out. should be fixed with the last commit to #30. At least it works locally on my machine ;) @kelunik can you confirm?

**Comment by kelunik** [comment]
Confirmed working after `service mysql restart`. Good work! :+1:
